### ISSUE TITLE
T1_Gestión de Proyectos de Software - Síntesis 

### ISSUE THREAD

**Issue by KarlaV0** [SistemasTecTlaxiaco/actividad-3-sintesis-KarlaV0#2]
[GP_Sintesis.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-KarlaV0/files/12527044/GP_Sintesis.pdf)

**Comment by MLR062998** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
